name: push_tunnel_client
description: Push notification tunnel client for censorship circumvention research.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cryptography: ^2.7.0
  http: ^1.2.0
